# Config file for automatic testing at travis-ci.org

sudo: true
language: python

matrix:
    include:
      - python: 2.7
      - python: 2.7
        env: SG_QT_LIBRARY=PySide
      - python: 2.7
        env: SG_QT_LIBRARY=PySide2

install:
  - pip install -e .
  - coverage run -m tk_build.cmd_line_tools.tk_ci_install

script:
  - coverage run --append -m tk_build.cmd_line_tools.tk_ci_tests

after_success: coveralls