# Config file for automatic testing at travis-ci.org

sudo: true
language: python

matrix:
    include:
      - python: 2.7
      - python: 2.7
        env: SG_QT_LIBRARY=PySide
      - python: 2.7
        env: SG_QT_LIBRARY=PySide2

install:
  # Pip install the current commit. This allows us to test the setup.py file. :)
  - pip install https://github.com/shotgunsoftware/tk-build/archive/${TRAVIS_COMMIT}.zip
  - tk-ci-install

script:
  - git diff origin/master
  - tk-ci-tests

# FIXME: Coverage is all wrong because our pytest-plugin loads the tk_build module, which breaks the
# coverage since the file has already been imported.
after_success: coveralls