# Config file for automatic testing at travis-ci.org

sudo: true
language: python

matrix:
    include:
      - python: 2.7
      - python: 2.7
        env: SG_QT_LIBRARY=PySide
      - python: 2.7
        env: SG_QT_LIBRARY=PySide2

install:
  - pip install -e .
  - tk-ci-install

script:
  - tk-ci-tests

# FIXME: Coverage is all wrong because our pytest-plugin loads the tk_build module, which breaks the
# coverage since the file has already been imported.
after_success: coveralls