# Copyright (c) 2020 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# Imports the shared Azure CI tools
resources:
  repositories:
    - repository: templates
      type: github
      name: shotgunsoftware/tk-ci-tools
      ref: refs/heads/master
      endpoint: shotgunsoftware

# We want builds to trigger for 3 reasons:
# - The master branch sees new commits
# - Each PR should get rebuilt when commits are added to it.
# - When we tag something
trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*
pr:
  branches:
    include:
    - "*"

# This pulls in a variable group from Azure. Variables can be encrypted or not.
variables:
- group: deploy-secrets

jobs:
- template: build-pipeline.yml@templates
  parameters:
    additional_repositories:
    - name: tk-framework-shotgunutils
    - name: tk-multi-publish2
    - name: tk-maya
    - name: tk-config-basic
      ref: v1.3.0
    - name: python-api

    extra_test_dependencies:
      # Replaces tk-toolchain with this branch's copy
      - "--editable ."

    # After the tests have run, run the integration tests.
    post_tests_steps:
      - bash: |
          python setup.py sdist
          python -m pip install -U dist/tk-toolchain-*.tar.gz
        displayName: Validate setup.py
